### PR TITLE
Added linear_interpolation

### LINKED ISSUE #26: Create a Speed Objective
# Purpose
The speed objective is used to determine the sailbot's cost when travelling at a particular "[point of sail](https://ubcsailbot.github.io/docs/main/reference/sailing/points_of_sail/)" and windspeed. This will penalize the sailbot from going above or below a particular speed. It safeguards the sailbot from possibly damaging the sailbot at high speeds or becoming stationary at lower speeds.

# Description

1. Determine how we will store the polar plot data and interpolate the sailbot speeds when our windspeed and angles are in between the discrete inputs. 
a. There are a number of ways to interpolate data points - Linear, Polynomial and Spline interpolation. Therefore, we will need to evaluate each method. 
2. Once we determine the initial speed at that point, determine the cost of the sailbot if the sailbot is within a particular speed range or not.
b. Do we use an inverse bell shape curve or linearly determine the cost? We will need to evaluate different methods of determining the costs.

Ensure you note the purpose of the functions, and what are the inputs and outputs of each of the functions. Note any restrictions on the inputs of the functions. The class function should be added to the path_objective.py file.

# Summary

- [ ] Construct a skeleton code of the speed objective
- [x] #28 
- [ ] Evaluate a suitable method for determining the cost of the sailbot at that particular speed.

# Resources
- https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/edit-v2/1860403201

### PR DESCRIPTION
**Pull request by Justin-Prasad**
### Description

- Resolves #26 

Added the interpolation function 

### Verification

- [Added test cases] 

### Resources

N/A

### CODE REVIEW

**Comment by jamenkaye** [comment]
@ / Justin-Prasad Running local pathfinding worked when I tried it just now, so I'm guessing some other dependency on your computer was out of date. If you're curious, you could try pulling the latest changes to the main branches of custom interfaces and sailbot workspace, and running the rebuild all task. I also converted our tests to the 4-argument form required, and made sure all the tests passed 👍

**Comment by jamenkaye** [comment]
@patrick-5546 We had to convert the `BOATSPEEDS` table to an numpy array to fix an error from mypy: "Value of type "object" is not indexable". Is this alright, or is there a better solution?

**Comment by jamenkaye** [comment]
@FireBoyAJ24 Just wanted to triple check the conventions you'll use with this function's inputs:
- windspeed: the **true windspeed** measured in km/h
- heading: which way the front of the boat is pointing. 0 degrees means pointing to the north, and angles increase clockwise. Bounded in [-180, 180]
- wind_direction: the direction that the **true wind** is _coming from_, where 0 degrees means wind coming from the north, and angles increase clockwise. Bounded in [-180, 180]. This requires a bit more calculation than the apparent wind measurement that we get from the wind sensors.

**Comment by patrick-5546** [comment]
> Is this alright, or is there a better solution?

Mypy doesn't like how `BOATSPEEDS` has lists that containing different types (int and float) even though Python allows this. Using a numpy array will cast everything to float, or you can just change all `0`'s to `0.0` so that everything is a float.

**Pull request merged**
